"""Create GeneralDataCafe table

Revision ID: 671f222fff81
Revises: 
Create Date: 2025-03-23 14:36:53.065647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671f222fff81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('climate_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('soil_humidity', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('expenses', sa.Float(), nullable=False),
    sa.Column('debts', sa.Float(), nullable=True),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_data_cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=50), nullable=False),
    sa.Column('actividad_principal', sa.String(length=50), nullable=False),
    sa.Column('otras_actividades', sa.String(length=200), nullable=True),
    sa.Column('tamano_produccion', sa.String(length=50), nullable=False),
    sa.Column('anos_actividad', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('coordenadas', sa.String(length=100), nullable=True),
    sa.Column('clima_preocupacion', sa.String(length=50), nullable=False),
    sa.Column('perdidas_clima', sa.String(length=200), nullable=True),
    sa.Column('tipo_ayuda', sa.String(length=50), nullable=False),
    sa.Column('frecuencia_chat', sa.String(length=50), nullable=False),
    sa.Column('comodidad_tecnologia', sa.String(length=50), nullable=False),
    sa.Column('aceptar_mejoras', sa.String(length=10), nullable=False),
    sa.Column('aceptar_terminos', sa.String(length=10), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_bovine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('cantidad_animales', sa.Integer(), nullable=False),
    sa.Column('meses_engorda', sa.Integer(), nullable=False),
    sa.Column('gastos_alimento', sa.Float(), nullable=False),
    sa.Column('pago_mano_obra', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('perdidas_animales', sa.Integer(), nullable=True),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('gastos_insumos', sa.Float(), nullable=False),
    sa.Column('pago_jornales', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('valor_maquinaria', sa.Float(), nullable=True),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_citrus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('toneladas_cosechadas', sa.Float(), nullable=False),
    sa.Column('tipos_citricos', sa.String(length=200), nullable=False),
    sa.Column('hectareas', sa.Float(), nullable=False),
    sa.Column('gastos_insumos', sa.Float(), nullable=False),
    sa.Column('pago_jornales', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('valor_maquinaria', sa.Float(), nullable=True),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_corn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('meses_cosecha', sa.Integer(), nullable=False),
    sa.Column('variedad_maiz', sa.String(length=100), nullable=False),
    sa.Column('hectareas', sa.Float(), nullable=False),
    sa.Column('gastos_insumos', sa.Float(), nullable=False),
    sa.Column('pago_jornales', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('valor_maquinaria', sa.Float(), nullable=True),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_eggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('cantidad_aves', sa.Integer(), nullable=False),
    sa.Column('porcentaje_produccion', sa.Float(), nullable=False),
    sa.Column('huevos_diarios', sa.Integer(), nullable=False),
    sa.Column('gastos_alimento', sa.Float(), nullable=False),
    sa.Column('pago_mano_obra', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data_pig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Float(), nullable=False),
    sa.Column('cantidad_animales', sa.Integer(), nullable=False),
    sa.Column('gastos_alimento', sa.Float(), nullable=False),
    sa.Column('pago_mano_obra', sa.Float(), nullable=False),
    sa.Column('gastos_servicios', sa.Float(), nullable=False),
    sa.Column('meses_engorda', sa.Integer(), nullable=False),
    sa.Column('perdidas_animales', sa.Integer(), nullable=True),
    sa.Column('dinero_disponible', sa.Float(), nullable=False),
    sa.Column('gastos_imprevistos', sa.Float(), nullable=False),
    sa.Column('total_deudas', sa.Float(), nullable=False),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data_cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_data_pig')
    op.drop_table('financial_data_eggs')
    op.drop_table('financial_data_corn')
    op.drop_table('financial_data_citrus')
    op.drop_table('financial_data_cafe')
    op.drop_table('financial_data_bovine')
    op.drop_table('general_data_cafe')
    op.drop_table('financial_record')
    op.drop_table('climate_data')
    op.drop_table('chat_log')
    op.drop_table('user')
    # ### end Alembic commands ###
